### ISSUE TITLE
Bug Report: Set ACRE channel number, LR Number channel # overrides short-range channel #

### ISSUE THREAD

**Issue by Aphex123** [unitedoperations/UnitedOperationsFramework#126] opened 2019-05-05 21:12 UTC
#### Description of issue

Setting Channel number in unit ACRE setting in framework does not change starting channel in game. 

#### Logs

https://pastebin.com/R3h7Etpr

#### Mission File(s)

https://www.dropbox.com/s/um8qg3d4ow45h3i/TVT62_Get_Greg_V1.Kidal.zip?dl=0

#### Steps to reproduce

1. Enable unit ACRE settings.
2. Give short range radio (possibly more, not tested)
3. Change channel number to other than 1.
4. Start mission in singleplayer, local multiplayer, or server multiplayer.
5. Bring up radio and observe channel number.

#### Expected behaviour

Radio will start on set channel.

#### Video and Screenshots

Unit ACRE settings: https://i.imgur.com/ukE21i8.jpg
In game with those settings: https://i.imgur.com/GVRixLO.jpg

**Comment by TrainDoctor** [comment] 2019-05-05 23:12
Could not reproduce on 1.0.6 or on latest commits to #124.
If you would be willing to test your mission on dev once #124 is merged, then we could confirm if this is may have been an oversight.

**Comment by TrainDoctor** [comment] 2019-05-06 01:26
#124 Has been merged. Testing release will be updated soon. Please check this version out to see if you encounter the same behavior.

**Comment by Aphex123** [comment] 2019-05-06 22:30
Further testing:
SR# set to 3.
LR# set to 5.
LRPACK# set to 7.

ingame with the above setting will yield:
SR on 5.
LR on 5.
LRPACK on 7.

RPT updated.
https://pastebin.com/R3h7Etpr

**Comment by TrainDoctor** [comment] 2019-05-08 03:25
Addressed in #131! Merged to dev and tested. Thanks for the report.

**Closed by TrainDoctor** 2019-05-08 03:25 UTC
Labels: general/bug, general/needs testing, other/clarification required
